### ISSUE TITLE
S10 losing parings every time BT is turned off

### ISSUE THREAD

**Issue by lekron42** [Magisk-Modules-Repo/libsecure_storage#5]
After updating to Android 10, my S10+ loses all pairings every time Bluetooth is turned off.. Is this known or am I the only one with this behaviour? 

Hopefully anyone can help, this is really annoying..

**Comment by lekron42** [comment]
For anyone having the same issue, use [this module](https://github.com/Magisk-Modules-Repo/BluetoothLibraryPatcher) instead, working perfectly!

**Comment by ianmacd** [comment]
This issue should have been fixed in v2.0, but if you upgraded to Android 10, you would need to reinstall the module. Otherwise, the module would continue to behave as if your device were an Android 9 device.

Nevertheless, moving to Arthur Trouillot's module is the better solution for the future.
